# Project configuration for your dbt project
name: "test"
version: "1.0.0"
config-version: 2

# Profile to be used for database connections
profile: "default"

# Path configurations for different dbt object types
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Target directory for compiled SQL files
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  test: # This refers to your project's namespace for models
    staging: # All staging models will be materialized as views
      materialized: view
    intermediate: # All intermediate models will be materialized as tables
      materialized: table
    final: # Final models will be materialized as tables
      materialized: table
# Default model materialization is 'view', but overridden for specific folders
