version: 2

sources:
  - name: sp500_analysis
    database: SP500_ANALYSIS
    schema: RAW_DATA
    tables:
      - name: raw_stock_prices
        description: "Raw stock price data from Google Sheets."
